version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fastapi_ordenes_db
    environment:
      POSTGRES_USER: programador_data
      POSTGRES_PASSWORD: password_seguro_123
      POSTGRES_DB: thelook_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U programador_data"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
